# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iPayBF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPayBF

	pod 'PopupDialog', '~> 1.1'
	pod 'Alamofire', '~> 5.4'

end
